# ------------------------------------------------------------------------------
# Modified from HRNet-Human-Pose-Estimation 
# (https://github.com/HRNet/HRNet-Human-Pose-Estimation)
# Copyright (c) Microsoft
# ------------------------------------------------------------------------------

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yacs.config import CfgNode as CN


# pose_resnet related params
FACE_RESNET = CN()
FACE_RESNET.NUM_LAYERS = 50
FACE_RESNET.DECONV_WITH_BIAS = False
FACE_RESNET.NUM_DECONV_LAYERS = 3
FACE_RESNET.NUM_DECONV_FILTERS = [256, 256, 256]
FACE_RESNET.NUM_DECONV_KERNELS = [4, 4, 4]
FACE_RESNET.FINAL_CONV_KERNEL = 1
FACE_RESNET.PRETRAINED_LAYERS = ['*']

# pose_multi_resoluton_net related params
FACE_HIGH_RESOLUTION_NET = CN()
FACE_HIGH_RESOLUTION_NET.PRETRAINED_LAYERS = ['*']
FACE_HIGH_RESOLUTION_NET.STEM_INPLANES = 64
FACE_HIGH_RESOLUTION_NET.FINAL_CONV_KERNEL = 1

FACE_HIGH_RESOLUTION_NET.STAGE2 = CN()
FACE_HIGH_RESOLUTION_NET.STAGE2.NUM_MODULES = 1
FACE_HIGH_RESOLUTION_NET.STAGE2.NUM_BRANCHES = 2
FACE_HIGH_RESOLUTION_NET.STAGE2.NUM_BLOCKS = [4, 4]
FACE_HIGH_RESOLUTION_NET.STAGE2.NUM_CHANNELS = [32, 64]
FACE_HIGH_RESOLUTION_NET.STAGE2.BLOCK = 'BASIC'
FACE_HIGH_RESOLUTION_NET.STAGE2.FUSE_METHOD = 'SUM'

FACE_HIGH_RESOLUTION_NET.STAGE3 = CN()
FACE_HIGH_RESOLUTION_NET.STAGE3.NUM_MODULES = 1
FACE_HIGH_RESOLUTION_NET.STAGE3.NUM_BRANCHES = 3
FACE_HIGH_RESOLUTION_NET.STAGE3.NUM_BLOCKS = [4, 4, 4]
FACE_HIGH_RESOLUTION_NET.STAGE3.NUM_CHANNELS = [32, 64, 128]
FACE_HIGH_RESOLUTION_NET.STAGE3.BLOCK = 'BASIC'
FACE_HIGH_RESOLUTION_NET.STAGE3.FUSE_METHOD = 'SUM'

FACE_HIGH_RESOLUTION_NET.STAGE4 = CN()
FACE_HIGH_RESOLUTION_NET.STAGE4.NUM_MODULES = 1
FACE_HIGH_RESOLUTION_NET.STAGE4.NUM_BRANCHES = 4
FACE_HIGH_RESOLUTION_NET.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
FACE_HIGH_RESOLUTION_NET.STAGE4.NUM_CHANNELS = [32, 64, 128, 256]
FACE_HIGH_RESOLUTION_NET.STAGE4.BLOCK = 'BASIC'
FACE_HIGH_RESOLUTION_NET.STAGE4.FUSE_METHOD = 'SUM'


MODEL_EXTRAS = {
    'face_resnet': FACE_RESNET,
    'face_high_resolution_net': FACE_HIGH_RESOLUTION_NET,
}
